spring:
  application:
    name: lucky-auth
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.78.210:8848
  redis:
    host: 8.130.78.210
    password:
    port: 6379
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.78.210:3306/mall?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 185450844
    hikari:
      max-lifetime: 500000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true # 默认false，在日志里显示执行的sql语句
    database: mysql
    database-platform: mysql
    hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
  main:
    allow-circular-references: true
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  application:
    name: Lucky-auth
    version: 1.0.0
  registry:
    address: nacos://8.130.78.210:8848